Fix FileHandle#map compatibility with GWT
libgdx/libgdx pull request #5767
Opened 2019-08-20 20:55 UTC by intrigus

https://github.com/libgdx/libgdx/pull/5259 doesn't work for me.
When compiling gdx-freetype-gwt I had to comment the part that used FileHandle.map() (https://github.com/intrigus/gdx-freetype-gwt/commit/93221646a8f56c37b6a3362558a8392189dec5ad#diff-11ed83df84f87aedd79b6b30b2c85b2aR93)

2019-08-21 09:42 UTC, PokeMMO commented
I think you are missing the ByteBuffer/FileChannel imports.

2020-08-27 19:13 UTC, MrStahlfelge commented
Yes, they are missing. Apart from that, I am surprised that this was not noticed before.

2020-08-27 19:14 UTC, MrStahlfelge requested changes
Add imports so the build succeeds.

2020-09-01 19:07 UTC, closed without merging

2020-10-20 11:56 UTC, intrigus commented
@MobiDevelop thanks for fixing it!