Add zipfile handle (implements #6212)
libgdx/libgdx pull request #6504
Opened 2021-04-20 08:13 UTC by dushechka

Adds a common zip-file handle and its resolver which enable reading from zip archives.
Borrowed from: https://gist.github.com/MobiDevelop/5514357#file-archivefilehandle-java.
This code has been tested on Windows 7x64.

2021-04-22 15:51 UTC, joshuaskelly commented on tests/gdx-tests/src/com/badlogic/gdx/tests/files/ZipFileHandleResolverTest.java
> +			ZipFile archive = new ZipFile(Gdx.files.internal(ZIP_FILE_PATH).file());
`FileHandle.file()` is unsupported on the GWT backend:
https://github.com/libgdx/libgdx/blob/5917a01534d7a2aa134e61b7c7975746e5ef19e4/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtFileHandle.java#L102

2021-04-22 17:40 UTC, MrStahlfelge requested changes
As you see, the GWT build fails. You can check locally by running `gradlew :tests:gdx-tests-gwt:compileGwt`

Probably when fixing the `file()` problem you will stumble across another problem. Probably you need to add an emu file for ZipFileHandle, just throwing exceptions.

2021-04-26 08:17 UTC, dushechka commented
@MrStahlfelge Maybe I'd better add a check for zip files to the [LwjglFiles](https://github.com/libgdx/libgdx/blob/5917a01534d7a2aa134e61b7c7975746e5ef19e4/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglFiles.java) (like in [DefaultAndroidFiles#getFileHandle](https://github.com/libgdx/libgdx/blob/ae57eee82b7c447abf1111c09cc6c2b439f2b9c4/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidFiles.java#L66)), so we could get access to zip files on desktop simply through [Gdx.files](https://github.com/libgdx/libgdx/blob/ae57eee82b7c447abf1111c09cc6c2b439f2b9c4/gdx/src/com/badlogic/gdx/Files.java#L25) and not break polymorphism? Then I'd rather move the test to the LWJGL and not make it common for all backends. Maybe later I could do the same for the Headless backend. GWT, in turn, will require its own implementation.

2021-05-04 06:59 UTC, dushechka commented
Submitted a separate pr 'cause this one has got too flooded because of the rebase: [#6518](https://github.com/libgdx/libgdx/pull/6518).

2021-05-04 11:24 UTC, MrStahlfelge commented
Then we can close this one?

2021-05-04 21:28 UTC, closed without merging