Implemented GL30's sRGB Format
libgdx/libgdx pull request #6553
Opened 2021-06-03 18:01 UTC by Timvisser1994

#5354 Feature request: add sRGB internal format of texture

Work done:

1. Added `SRGB` format support for `Gdx2DPixmap`. This format lives inside of `GL30`.
2. Code cleanup (changed `if-statements` to `switch-statements` for better readability). This should also enable the compiler to optimize better.

2021-06-24 15:30 UTC, mgsx-dev requested changes
@Timvisser1994 your code doesn't work for me, it crashes, did you tested it? it's better to provide a test case for new features. Also, as you can read in the [issue comment](https://github.com/libgdx/libgdx/issues/5354#issuecomment-867729632) i just posted, i don't think it's the right approach of implementing it.

Feel free to change your PR (and provide test case) or close it if you're not sure how to do that.

2021-06-24 18:21 UTC, Timvisser1994 commented
@mgsx-dev You are right... this does not work.

![image](https://user-images.githubusercontent.com/2553764/123313037-5a485f80-d529-11eb-9c0f-c756bb41460e.png)

And I agree with you comment, will rework this PR.

2022-01-18 02:54 UTC, badlogic requested changes
Looks good in general, except for turning the `int` constants into `short` constants. That's an unnecessary breaking change.

Also the CHANGES file should note that this new pixmap format was added.

2022-01-18 02:54 UTC, badlogic commented on gdx/src/com/badlogic/gdx/graphics/g2d/Gdx2DPixmap.java
> +	public static final short GDX2D_FORMAT_ALPHA = 1;
Why `short`?

2023-10-17 08:53 UTC, closed without merging