Make capitalization of "libGDX" consistent with the branding guidelines by replacing some instances of "LibGDX" and "libgdx", plus some other very minor inconsistencies
libgdx/libgdx pull request #6591
Opened 2021-07-07 20:29 UTC by Frosty-J

> The name “libGDX” always starts with a lower-case `l`, even at the beginning of a sentence. `GDX` is always written in upper-case letters.

https://libgdx.com/brand/

If we're going to go with this, let's at the very least have the README follow it.

Most of these changes are in comments and the likes, so hopefully nothing will break.

This is not a Find & Replace job - I left some things alone, such as historical changelogs and someone's monologue in `AndroidLiveWallpaper.java`.

I agree to the contributor licence, yadda yadda - just forge my signature.

2021-07-07 21:05 UTC, tommyettinger requested changes
I just think we need to verify that the CLA email process is either checked by a person or by a case-insensitive filter before we change the email procedure. Other than that, everything looks fine.

2021-07-07 21:05 UTC, tommyettinger commented on .github/CONTRIBUTING.md
> +libGDX is licensed under the [Apache 2.0 license](http://en.wikipedia.org/wiki/Apache_License). Before we can accept code contributions, we need you to sign our [contributor license agreement](https:
We might need to verify that the CLA email filter is case-insensitive, otherwise using a different subject line might inadvertently bypass the inbox.

2021-07-08 15:00 UTC, 00-Evan commented
I can confirm that the inbox seems to work with the title "[libGDX] CLA", I just received a reply email from Mario for my recent CLA submission.

2021-07-08 15:23 UTC, crykn approved these changes

2021-07-08 21:33 UTC, tommyettinger approved these changes

2021-07-08 21:35 UTC, merged