Audio: Add pause/resume methods to AudioDevice.
libgdx/libgdx pull request #6595
Opened 2021-07-12 09:24 UTC by PokeMMO

* Only really useful for Android to save resources when not playing any audio.

2021-07-27 19:03 UTC, mgsx-dev requested changes
please add something to the CHANGES file (as a breaking change for custom AudioDevice implementations)

2021-07-27 19:17 UTC, PokeMMO commented
I miss having default interface methods.

2021-08-02 13:57 UTC, mgsx-dev approved these changes

2021-08-12 08:27 UTC, crykn commented
The changes look good to me, but what exactly are the comments in `OpenALAudioDevice#pause()` and `#resume()` for?

2021-09-06 01:26 UTC, PokeMMO commented
> The changes look good to me, but what exactly are the comments in `OpenALAudioDevice#pause()` and `#resume()` for?

Just to explain why no code is necessary in those methods. There's no point to actually pause the OpenAL output as it will pause itself when you stop sending it samples.

2021-09-22 07:26 UTC, merged