Update to LWJGL 3.3.0
libgdx/libgdx pull request #6721
Opened 2021-12-08 18:34 UTC by PokeMMO

2021-12-08 22:21 UTC, tommyettinger requested changes
These lines should also be changed:
https://github.com/libgdx/libgdx/blob/master/fetch.xml#L13-L14
I guess we still use Ant in places.

2021-12-09 04:06 UTC, tommyettinger approved these changes
Looks good! I'm not 100% sure of what jnigen does in this same file (line 11), but should it be changed to 2.2.1? That might be better in a separate PR, unless it's related here.

2021-12-09 10:24 UTC, Tom-Ski approved these changes

2021-12-09 12:58 UTC, PokeMMO commented
The only changes in jnigen 2.2.1 were in the gradle plugin, which this doesn't use.

2021-12-09 12:58 UTC, merged